### ISSUE TITLE
RAG 논문을 읽어보지는 않았지만, 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by SungKyuHong** [jjlee6496/RAG#1]
- 문장 10개의 케이스 이외에도 여러 케이스들에 대해서도 고민해보는 것은 어떨까요..?
- 각 문장들별로 길이 수에 따른 성능의 영향은 없나요? 만약 존재한다면, 성능에 따른 문장 길이에 대한 분포도 시각화해보면 좋은 인사이트를 얻을 수 있을 것 같은 느낌이 드네용
- Feature Store 로써의 활용가치도 있을까요?

**Comment by jjlee6496** [comment]
* 문서에서 생성된 질문으로만 평가해 봤는데 상관없는 질문도 추가해서 평가해보겠습니다.
* 좋은 의견 감사합니다! 좀 더 긴 문장들을 넣어서 실험해보겠습니다
* 하나의 문서로만 실험해봤지만 문서 구조에 따라 효율성 차이가 발생할 수 있다고 생각이 들었습니다. 실험에 사용한 문서의 경우 짧고 하나의 맥락으로 이어지는 문서여서, 방식에 따라 LLM에 들어가는 context가 그렇게 차이가 나지 않아 RAG 방식에 따른 차이가 그렇게 크지 않았다고 생각이 듭니다. 따라서 성격이 다른 여러 문서에 실험해보면서 기록해둔다면 Feature Store로서 활용 가능하다고 생각이 듭니다!

**Comment by SungKyuHong** [comment]
넵, 좋습니다.. 여러 케이스에 대한 실험을 진행한다면 WanDB 같은 MLOps 플랫폼도 고려해보시는걸 추천드립니다...
